// Team codes match ESPN abbreviations. `name` is what goes on the board.
export const TEAMS = {
  ARI: { name: 'Cardinals', city: 'Arizona', color: '#97233F' },
  ATL: { name: 'Falcons', city: 'Atlanta', color: '#A71930' },
  BAL: { name: 'Ravens', city: 'Baltimore', color: '#241773' },
  BUF: { name: 'Bills', city: 'Buffalo', color: '#00338D' },
  CAR: { name: 'Panthers', city: 'Carolina', color: '#0085CA' },
  CHI: { name: 'Bears', city: 'Chicago', color: '#C83803' },
  CIN: { name: 'Bengals', city: 'Cincinnati', color: '#FB4F14' },
  CLE: { name: 'Browns', city: 'Cleveland', color: '#4B2A17' },
  DAL: { name: 'Cowboys', city: 'Dallas', color: '#003594' },
  DEN: { name: 'Broncos', city: 'Denver', color: '#FB4F14' },
  DET: { name: 'Lions', city: 'Detroit', color: '#0076B6' },
  GB: { name: 'Packers', city: 'Green Bay', color: '#203731' },
  HOU: { name: 'Texans', city: 'Houston', color: '#03202F' },
  IND: { name: 'Colts', city: 'Indianapolis', color: '#002C5F' },
  JAX: { name: 'Jags', city: 'Jacksonville', color: '#006778' },
  KC: { name: 'Chiefs', city: 'Kansas City', color: '#E31837' },
  LV: { name: 'Raiders', city: 'Las Vegas', color: '#000000' },
  LAC: { name: 'Chargers', city: 'LA', color: '#0080C6' },
  LAR: { name: 'Rams', city: 'LA', color: '#003594' },
  MIA: { name: 'Dolphins', city: 'Miami', color: '#008E97' },
  MIN: { name: 'Vikings', city: 'Minnesota', color: '#4F2683' },
  NE: { name: 'Pats', city: 'New England', color: '#002244' },
  NO: { name: 'Saints', city: 'New Orleans', color: '#A08A58' },
  NYG: { name: 'Giants', city: 'New York', color: '#0B2265' },
  NYJ: { name: 'Jets', city: 'New York', color: '#125740' },
  PHI: { name: 'Eagles', city: 'Philadelphia', color: '#004C54' },
  PIT: { name: 'Steelers', city: 'Pittsburgh', color: '#C69200' },
  SF: { name: '49ers', city: 'San Francisco', color: '#AA0000' },
  SEA: { name: 'Seahawks', city: 'Seattle', color: '#3C8A2E' },
  TB: { name: 'Bucs', city: 'Tampa Bay', color: '#D50A0A' },
  TEN: { name: 'Titans', city: 'Tennessee', color: '#4B92DB' },
  WSH: { name: 'Commies', city: 'Washington', color: '#5A1414' },
};

export const teamName = (code) => (TEAMS[code] ? TEAMS[code].name : code);
